luzdohorto/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :colabs
  resources :colaboradors
  resources :instituicos

  get 'cont_users/index'
  get 'cont_users/new'
  get 'cont_users/edit'


  post 'savenew', to: 'users#savenew'

  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

  resources :cadastros

  resources :relatorios

  match 'download' => 'relatorios#download', via: [:get, :post]
  #post 'download'=> 'relatorios#download'


  root 'cadastros#index'

  #get '*path' => redirect('/')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

luzdohorto/app/models/cadastro.rb
class Cadastro < ActiveRecord::Base
	belongs_to :user
	has_many :colabs
	paginates_per 20

  validates_presence_of :id_cliente_coelce, :digito_verificador_cliente_coelce, :codigo_ocorrencia, :valor, :parcelas
  validates :id_cliente_coelce, length: { maximum: 10, too_long: "é maior que o aceitável de 10 digitos. Verifique e tente novamente." }
  validates :digito_verificador_cliente_coelce, length: { maximum: 2, too_long: "é maior que o aceitável de 2 digitos. Verifique e tente novamente." }
  validates :codigo_ocorrencia, length: { maximum: 2, too_long: "é maior que o aceitável de 2 digitos. Verifique e tente novamente." }
  validates :parcelas, length: { maximum: 2, too_long: "é maior que o aceitável de 2 digitos. Verifique e tente novamente." }
	
  def self.assocCadColab (cadastro_id, colaborador_id)
  		colab = Colab.new
  		colab.cadastro_id = cadastro_id
  		colab.colaborador_id = colaborador_id
  		colab.save
  	end

  	def self.search(query, user)
      if query.present? and user.role == "admin"
      		where(['id_cliente_coelce::text LIKE :query OR
            	valor::text LIKE :query OR livre::text LIKE :query', query: "%#{query}%"])
    	elsif query.present?
    		where(:user_id => user.id).where(['id_cliente_coelce::text LIKE :query OR
            	valor::text LIKE :query OR livre::text LIKE :query', query: "%#{query}%"])
    	elsif user.role == "admin"
    		all
    	else
    		where(:user_id => user.id)
    	end
    end
	
end

luzdohorto/app/controllers/cadastros_controller.rb
class CadastrosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_cadastro, only: [:show, :edit, :update, :destroy]
   
  # GET /cadastros
  # GET /cadastros.json
  def index

    @search_query = params[:q]
    
    @cadastros = Cadastro.order('created_at DESC').search(@search_query, current_user).page params[:page]
    # if params[:search]
    #   @cadastros = Cadastro.where("id_cliente_coelce like ?", "%#{params[:search]}")
    #   elsif :user_role == "admin"      
    #    @cadastros = Cadastro.joins(:user).order("created_at DESC").page params['page']
    #   else   
    #    @cadastros = Cadastro.where(:user_id => current_user.id).order("created_at DESC").page params['page']        
    # end
  end

  # GET /cadastros/1
  # GET /cadastros/1.json
  def show
  end

  # GET /cadastros/new
  def new
    @cadastro = current_user.cadastros.build
  end
  

  # GET /cadastros/1/edit
  def edit
  end

  # POST /cadastros
  # POST /cadastros.json
  def create
    @cadastro = current_user.cadastros.build(cadastro_params)
    
    respond_to do |format|
      if @cadastro.save
        Cadastro.assocCadColab(@cadastro.id, params[:colaborador][:colaborador_id])
        format.html { redirect_to @cadastro, notice: 'Cadastro criado com sucesso.' }
        format.json { render :show, status: :created, location: @cadastro }
           
      else
        format.html { render :new }
        format.json { render json: @cadastro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cadastros/1
  # PATCH/PUT /cadastros/1.json
  def update
    respond_to do |format|
      if @cadastro.update(cadastro_params)
        format.html { redirect_to @cadastro, notice: 'Cadastro atualizado com sucesso..' }
        format.json { render :show, status: :ok, location: @cadastro }
      else
        format.html { render :edit }
        format.json { render json: @cadastro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cadastros/1
  # DELETE /cadastros/1.json
  def destroy
    @cadastro.destroy
    respond_to do |format|
      format.html { redirect_to cadastros_url, notice: 'Cadastro excluído com sucesso..' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cadastro
      @cadastro = Cadastro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cadastro_params
      params.require(:cadastro).permit(:id_cliente_coelce, :digito_verificador_cliente_coelce, :codigo_ocorrencia, :data_ocorrencia, :valor, :parcelas, :id_cliente_parceira, :codigo_produto, :codigo_empresa_parceira, :livre)
    end
end

luzdohorto/app/helpers/cadastros_helper.rb
module CadastrosHelper
end

luzdohorto/app/views/cadastros/_form.html.erb
<%= form_for(cadastro) do |f| %>
<% if cadastro.errors.any? %>
<center>
  <div id="error_explanation" class="alert alert-danger" style="width: 500px">
    <h2><%= pluralize(cadastro.errors.count, "erro(s)") %> encontrado(s):</h2>
    
      <% cadastro.errors.full_messages.each do |message| %>
      <p><%= message %></p>
      <% end %>
    
  </div>
</center>
<% end %>

    <div class="page-header">
      <h1 align="center" class="enunciado">Doador</h1>
    </div>
    <br>
      <div class="container-fluid col-xl-4 rounded border border-secondary" style="background-color: #FAFAFA; height: 600px; width: 600px;">
      <br>
        <form style="vertical-align: middle;">      
          <div class="form-group row">            
             <label class="col-sm-4 col-form-label font-weight-bold textolabels">ID do cliente ENEL</label>       
              <div class="col-md-8">
                <%= f.number_field :id_cliente_coelce, class: "form-control"%>  
              </div>          
          </div>
           <div class="form-group row">                         
                <label class="col-sm-4 col-form-label font-weight-bold textolabels">Digito Verificador  </label>
                <div class="col-md-8">
                  <%= f.number_field :digito_verificador_cliente_coelce, class: "form-control "%>              
                </div>
          </div>
          <div class="form-group row">                         
                <label class="col-sm-4 col-form-label font-weight-bold textolabels ">Código de ocorrência  </label>
                <div class="col-md-8">
                  <%= f.number_field :codigo_ocorrencia, class: "form-control" %>              
                </div>
          </div> 
          <div class="form-group row">               
                <label class="col-sm-4 col-form-label font-weight-bold textolabels">Data de Ocorrência  </label>
                <div class="col-md-8">
                  <%= f.date_select :data_ocorrencia, :order => [:day, :month, :year], class:'form-control', type:"date"%>            
                </div>
         </div>
          <div class="form-group row">               
              <label class="col-sm-4 col-form-label font-weight-bold textolabels">Valor  </label>
              <div class="col-md-8">
                <%= f.number_field :valor, :step => 0.01, class: "form-control"%>
              </div>
          </div>
          <div class="form-group row">
              <label class="col-sm-4 col-form-label font-weight-bold textolabels">Número de Parcelas  </label>
              <div class="col-md-8">
                <%= f.number_field :parcelas, class: "form-control"%>          
              </div>
          </div>
          <div class="form-group row">
             <label class="col-sm-4 col-form-label font-weight-bold textolabels">Caso haja, digite o número de protocolo  </label>
             <div class="col-md-8">
              <%= f.text_area :livre, class:'form-control'%>
            </div>
          </div>
          <div class="form-group row">
              <label class="col-sm-4 col-form-label font-weight-bold textolabels">Caso haja um colaborador, selecione</label>
              <div class="col-md-8">
                <%= select("colaborador", "colaborador_id", Colaborador.all.collect {|p| [ p.nomereduzido, p.id ] }, { include_blank: false, prompt: true}, class:'form-control') %>
              </div>
          </div>  
          <br>
          <div class="actions" align="center">
            <%= f.submit "Salvar", class:"btn btn-primary"%>
            <%=link_to 'Cancelar', root_path, class: 'btn btn-warning'%>
          </div>
          </form>     
    </div>

  <% end %>

luzdohorto/app/views/cadastros/_search.html.erb
<center>
<p style="font-size: 20px" class="enunciado">Busca</p>
	<%= form_tag cadastros_path, method: :get, class: 'search' do %>
  		<%= text_field_tag :q, @search_query ,class: "form-control col-5", placeholder:'Digite o número do cliente, valor ou número de protocolo' %>  
  		<br>
  		<%= submit_tag "Buscar", :class => 'btn btn-outline-primary btn-sm' %>  <%= link_to 'Limpar', root_path, :class => 'btn btn-outline-info btn-sm'	%>
	<% end %>
</center>

luzdohorto/app/views/cadastros/edit.html.erb
<%= render 'form', cadastro: @cadastro %>

luzdohorto/app/views/cadastros/index.html.erb
<script src="//rawgithub.com/stidges/jquery-searchable/master/dist/jquery.searchable-1.0.0.min.js"></script>
 
  <div class="container">
    <div class="row">
      <div class="col-lg-12">        
          <h1 align="center" class="enunciado">Cadastros</h1>       
      </div>
    </div>
    <br>
    <center>
        <%= render 'search' %> 
    </center>
  <br>
  <br>
  <br>
  <div>
    <div class="col-lg-12 ">
      <table class="table table-striped ">
        <thead >
          <tr class="titulotabela" style="height: 30px;">
            <th class="colunacontador"  style="border-color: black">#</th>           
            <th style="border-color: black; text-align: center;">Id Cliente ENEL</th>
            <th style="border-color: black; text-align: center;" width="20px">Codigo Ocorrencia</th>
            <th style="border-color: black; text-align: center;" width="100px">Valor</th>
            <th style="border-color: black; text-align: center;">Parcelas</th>
            <%if current_user.role == "admin" %>
            <th style="border-color: black; text-align: center;">Autor</th>
            <%end%>
            <th style="border-color: black; text-align: center;">Data do Cadastro</th>   
            <th class="border-right-1" colspan="2" style="border-color: black; text-align: center;">Protocolo</th>            
            <th style="border-color: black; text-align: center;"><h4><span class="badge badge-pill badge-info">Total de registros <span class="badge badge-warning"> <%= @cadastros.total_count %> </span></span></h4></th>     
            
          </tr>
        </thead>
        <tbody>
       
          <% @cadastros.each_with_index do |cadastro, x| %>
          <tr>
            <%if current_user.id == cadastro.user_id || policy(@cadastros).index? %>
            <td class="colunacontador"><%= x + 1 %></td>
            <td class="conteudotabela"><%= cadastro.id_cliente_coelce %></td>
            <td class="conteudotabela"><%= cadastro.codigo_ocorrencia %></td>                  
            <td class="conteudotabela"> R$ <%= cadastro.valor %></td>
            <td align="center" class="conteudotabela"><%= cadastro.parcelas %></td>
            <%if current_user.role == "admin"%>
            <td><span class="badge badge-pill badge-info"><%= cadastro.user.username%></span></td>
            <% end %>
            <td align="center" class="conteudotabela"><%= cadastro.data_ocorrencia.strftime("%d / %m / %Y") %></td>
            
            <td align="center" colspan="2" class="conteudotabela "><%= cadastro.livre %></td>            
            <td align="center">
              <%= link_to'Ver', cadastro,class: 'btn btn-info btn-sm' %>
              <%= link_to 'Editar', edit_cadastro_path(cadastro),class: 'btn btn-success btn-sm'%>  
            </td>          
        </tr>
        <% end %>
        <% end %>
      </tbody>
    </table>    
  </div>  
</div>
<div class="paginacao"><%= paginate @cadastros %></div>

luzdohorto/app/views/cadastros/new.html.erb
<%= render 'form', cadastro: @cadastro %>

luzdohorto/app/views/cadastros/show.html.erb
<div class="container-fluid col-xl-4 rounded border border-secondary" style="background-color: #FAFAFA; font-size: 15px">
  <div> <br> <br> <h1 align="center" class="enunciado"> Informações </h1></div>
  <br>
  <br>
  <div class="container-fluid col-xl-10">
    <div >
      <div><b class="textoshow">Id Cliente:</b>&nbsp;<texto> <%= @cadastro.id_cliente_coelce %> </texto></div>
    </div>
    <br>
    <div>
      <div ><b class="textoshow">Digito Verificador Cliente Coelce:</b>&nbsp;<texto>  <%= @cadastro.digito_verificador_cliente_coelce %></texto></div>
    </div>
    <br>
    <div>
      <div ><b class="textoshow">Código Ocorrência:</b>&nbsp;<texto> <%= @cadastro.codigo_ocorrencia %></texto></div>
    </div>
    <br>
    <div>
      <div><b class="textoshow">Data Ocorrência:</b>&nbsp;<texto> <%= @cadastro.data_ocorrencia.strftime("%d / %m / %Y")%></texto></div>
    </div>
    
    <br>
    <div>
      <div><b class="textoshow">Valor:</b>&nbsp;<texto> R$ <%= @cadastro.valor %></texto></div>
    </div>
    <br>
    <div>
      <div><b class="textoshow">Parcelas:</b>&nbsp;<texto>   <%= @cadastro.parcelas %></texto></div>
    </div>
    <br>
    <div>
      <div><b class="textoshow">Protocolo:</b>&nbsp;<texto>  <%= @cadastro.livre %></texto> </div>
    </div>
    <br>
    <% if !@cadastro.colabs.blank? %>
        <div>
          <div><b class="textoshow">Colaborador:</b><texto> <%= @cadastro.colabs[0].colaborador.nomereduzido %></texto></div>
        </div>
    <% end %>
    <br>
    <td>

    <center>
      <%=link_to 'Voltar', root_path, class: 'btn-sm btn-info'%>
      <%=link_to 'Cadastrar Novamente', new_cadastro_path, class: 'btn-sm btn-success'%>
      <!-- <% if current_user.role == "admin" %>
      <%= link_to 'Excluir', cadastro_path(@cadastro), class: 'btn btn-danger', method: :delete, data: { confirm: 'Tem certeza que deseja excluir o registro?' } %> -->

    </center>
    <br>
    </td>
  </div>
  <% end %>
</div>
</div>