luzdohorto/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :colabs
  resources :colaboradors
  resources :instituicos

  get 'cont_users/index'
  get 'cont_users/new'
  get 'cont_users/edit'


  post 'savenew', to: 'users#savenew'

  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

  resources :cadastros

  resources :relatorios

  match 'download' => 'relatorios#download', via: [:get, :post]
  #post 'download'=> 'relatorios#download'


  root 'cadastros#index'

  #get '*path' => redirect('/')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

luzdohorto/app/models/colaborador.rb
class Colaborador < ApplicationRecord
  belongs_to :user
  has_many :colabs
  has_many :colaborador, through: :colabs 
  paginates_per 20

  validates_presence_of :nomecompleto, :telefone, :endereco, :nomereduzido
  validates :nomecompleto, uniqueness: true
  validates :nomereduzido, uniqueness: true
 

end

luzdohorto/app/controllers/colaboradors_controller.rb
class ColaboradorsController < ApplicationController
  before_action :set_colaborador, only: [:show, :edit, :update, :destroy]

  # GET /colaboradors
  # GET /colaboradors.json
  def index
    @colaboradors = Colaborador.joins(:user).all.order("nomecompleto ASC").page params['page']
  end

  # GET /colaboradors/1
  # GET /colaboradors/1.json
  def show
  end

  # GET /colaboradors/new
  def new
    @colaborador = Colaborador.new
  end

  # GET /colaboradors/1/edit
  def edit
  end

  # POST /colaboradors
  # POST /colaboradors.json
  def create
    @colaborador = Colaborador.new(colaborador_params.merge(user_id: current_user.id))

    respond_to do |format|
      if @colaborador.save
        format.html { redirect_to @colaborador, notice: 'Colaborador cadastrado com sucesso.' }
        format.json { render :show, status: :created, location: @colaborador }
      else
        format.html { render :new }
        format.json { render json: @colaborador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /colaboradors/1
  # PATCH/PUT /colaboradors/1.json
  def update
    respond_to do |format|
      if @colaborador.update(colaborador_params)
        format.html { redirect_to @colaborador, notice: 'Colaborador atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @colaborador }
      else
        format.html { render :edit }
        format.json { render json: @colaborador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colaboradors/1
  # DELETE /colaboradors/1.json
  def destroy
    @colaborador.destroy
    respond_to do |format|
      format.html { redirect_to colaboradors_url, notice: 'Colaborador excluído com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_colaborador
      @colaborador = Colaborador.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def colaborador_params
      params.require(:colaborador).permit(:nomecompleto, :telefone, :endereco, :nomereduzido, :user_id)
    end
end

luzdohorto/app/helpers/colaboradors_helper.rb
module ColaboradorsHelper
end

luzdohorto/app/views/colaboradors/_form.html.erb
<%= form_for(@colaborador) do |f| %>
  <% if colaborador.errors.any? %>
<center>
  <div id="error_explanation" class="alert alert-danger" style="width: 500px">
      <h2><%= pluralize(colaborador.errors.count, "erro(s)") %> encontrado(s):</h2>


      <% colaborador.errors.full_messages.each do |message| %>
       <p><%= message %></p>
      <% end %>

  </div>
</center>
  <% end %>


  <br>
  <div class="container-fluid col-xl-4 rounded border border-secondary" style="background-color: #FAFAFA;">
      <h1 align="center" class="enunciado">Colaborador</h1>
    <br>
    <form >
      <div class="form-group row" >
          <label class="col-sm-4 col-form-label textolabels">Nome Completo</label>
          <div class="col-md-8">
            <%= f.text_field :nomecompleto, class: "form-control" %>
          </div>
      </div>
        <div class="form-group row" >
          <label class="col-sm-4 col-form-label textolabels">Telefone</label>
            <div class="col-md-8">
              <%= f.text_field :telefone, class: "form-control" %>
            </div>
          </div>
        <div class="form-group row">
          <label class="col-sm-4 col-form-label textolabels">Endereço</label>
          <div class="col-md-8" >
            <%= f.text_field :endereco, class: "form-control" %>
          </div>
        </div>
          <div class="form-group row">
            <label class="col-sm-4 col-form-label textolabels">Nome reduzido</label>
            <div class="col-md-8">
              <%= f.text_field :nomereduzido, class: "form-control" %>
            </div>
          </div>

   </form>


  <div align="center">
    <%= f.submit "Salvar", :class => 'btn btn-success btn-sm'%>
    <%= link_to 'Voltar', colaboradors_path, :class => 'btn btn-warning btn-sm'%>
  </div>
<% end %>
<br>
</div>

luzdohorto/app/views/colaboradors/edit.html.erb
<%= render 'form', colaborador: @colaborador %>

luzdohorto/app/views/colaboradors/index.html.erb
<div class="container">
    <div class="row">
     <div class="col-lg-12">
        <h1 align="center" class="enunciado">Colaboradores</h1>
      </div>
    </div>
    <br>
   <div class="row">
    <div class="col-lg-12">
      <center>
        <%= link_to 'Cadastrar novo Colaborador', new_colaborador_path, class: 'btn btn-primary' %>
        <% if current_user.role == "admin"%>
        <%= link_to 'Relatório dos Colaboradores', colabs_path, class: 'btn btn-warning' %>
        <% end %>
      </center>
      <br>
      <table class="table table-striped">
         <thead>
            <tr>
              <th style="text-align: center;">Nome Completo</th>
              <th style="text-align: center;">Telefone</th>

              <th style="text-align: center;">Nome reduzido</th>
            </tr>
          </thead>

          <tbody>
            <% @colaboradors.each do |colaborador| %>
              <tr style="font-size: 15px">
                <td class="conteudotabela"><%= colaborador.nomecompleto %></td>
                <td class="conteudotabela"><%= colaborador.telefone %></td>

                <td class="conteudotabela"><%= colaborador.nomereduzido %></td>
                <td class="conteudotabela"><%= link_to 'Ver', colaborador, class: 'btn btn-info btn-sm' %>
                <%= link_to 'Editar', edit_colaborador_path(colaborador),class: 'btn btn-success btn-sm' %>
                </td>
                <!-- <%if current_user.role == "admin" %>
                  <%= link_to 'Excluir', colaborador, method: :delete, data: { confirm: 'Tem certeza que deseja excluir?' }, class:'btn btn-danger btn-sm' %></td>
                <%end%> -->
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
<center><%= paginate @colaboradors %></center>
<br>
</div>

luzdohorto/app/views/colaboradors/new.html.erb
<%= render 'form', colaborador: @colaborador %>

luzdohorto/app/views/colaboradors/show.html.erb
<div class="container-fluid col-xl-4  rounded border border-secondary" style="background-color: #FAFAFA;">
<br>
<h1 align="center" class="enunciado ">Informações do Colaborador </h1>
<br>
<br>
    <div>
      <div><b class="textoshow">Nome Completo: </b>&nbsp;<texto> <%= @colaborador.nomecompleto %></texto> </div>
    </div>
    <br>
    <div>
      <div><b class="textoshow">Telefone:</b>&nbsp; <texto><%= @colaborador.telefone %></texto></div>
    </div>
    <br>
    <div>
      <div><b class="textoshow">Endereço: </b> &nbsp;<texto><%= @colaborador.endereco %></texto> </div>
    </div>
    <br>
    <div >
      <div ><b class="textoshow">Nome Reduzido:&nbsp; </b><texto> <%= @colaborador.nomereduzido %></texto> </div>
    </div>
    <br>
    <div>
      <div><b class="textoshow">Cadastrado Por: </b>&nbsp;<texto> <%= @colaborador.user.username %></texto> </div>
    </div>

    <br>
   <center>
     <td>
        <%= link_to 'Editar', edit_colaborador_path(@colaborador), class:"btn btn-success" %>
        <%= link_to 'Voltar', colaboradors_path, class:"btn btn-warning" %>
        <%= link_to 'Cadastrar Novo', new_colaborador_path, class:"btn btn-info" %>
  </center>
  <br>
  </div>
</div>