luzdohorto/config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  # mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :colabs
  resources :colaboradors
  resources :instituicos

  get 'cont_users/index'
  get 'cont_users/new'
  get 'cont_users/edit'


  post 'savenew', to: 'users#savenew'

  devise_for :users, controllers: {
        sessions: 'users/sessions'
      }

  resources :cadastros

  resources :relatorios

  match 'download' => 'relatorios#download', via: [:get, :post]
  #post 'download'=> 'relatorios#download'


  root 'cadastros#index'

  #get '*path' => redirect('/')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

luzdohorto/app/views/layouts/_user_navbar.html.erb
  <nav class="navbar  bg-light fixed-top">
      <div class="container col-sm-8">
         <div class="row">
            <a><%=link_to 'Luz Do Horto ', root_path, class:"textonavbrand" %></a>
          </div>
          <div class="row">
              <a ><%=link_to 'Inicio', root_path, class:"textonavbar" %></a>&nbsp;&nbsp;&nbsp;&nbsp;
              <a><%=link_to 'Cadastrar' , new_cadastro_path, class:"textonavbar" %>&nbsp;&nbsp;&nbsp;&nbsp;</a>
              <% if current_user.role == "admin"%>
                 <a><%=link_to 'Usuários', cont_users_index_path, class:"textonavbar" %>&nbsp;&nbsp;</a>
                 <a><%=link_to 'Relatórios', relatorios_path, class:"textonavbar"%> &nbsp;&nbsp;</a>
                 <a><%=link_to 'Novo Relatório', new_relatorio_path, class:"textonavbar"%>&nbsp;&nbsp;</a>
                 <a><%=link_to 'Instituição', instituicos_path, class:"textonavbar"%>&nbsp;&nbsp;</a>
                 
              <% end %>
              <a><%=link_to 'Colaboradores', colaboradors_path, class:"textonavbar"%>&nbsp;&nbsp;&nbsp;&nbsp;</a>
              <a><%=link_to "Editar Perfil", edit_user_registration_path, class:"textonavbar" %>&nbsp;&nbsp;&nbsp;&nbsp;</a>
              <a><%=link_to "Sair", destroy_user_session_path, :method => :delete, class:"textonavbar"%>&nbsp;&nbsp;&nbsp;&nbsp;</a>
          </div>
      </div>
  </nav>
  <br>
  <br>
  <br>
  <br>
  <br>

luzdohorto/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Luz do Horto</title>
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link href="https://fonts.googleapis.com/css?family=Signika" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Signika" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Doppio+One" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Encode+Sans+Expanded" rel="stylesheet">
  <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"> -->

  <%= favicon_link_tag 'icon.png' %>
  <%=stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%=javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%=csrf_meta_tags %>
</head>
<% if user_signed_in? %>
   <%= render 'layouts/user_navbar' %>
<% end %>
<body >
  <div id="content">
    <% if notice.present? %>
     <center><div class="alert alert-success dismissible" role="alert" style="width: 700px">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
        <p id="notice" style="font-size: 20px" align="center"><%= notice %></p>
      </div></center>
    <% end %>
    <% if alert.present? %>
      <center><div class="alert alert-danger dismissible" role="alert" style="width: 700px;">
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
        <p id="notice" style="font-size: 15px"><p id="alert"><%= alert %></p>
      </div></center>
    <% end %>
  </div>
  <div >
   <%= yield %>
  </div>
</body>
    <br>
    <div class="logo">
      <center>
      <hr class="linha " width="100%">      
    </div>
</html>